### ISSUE TITLE
GCC GNAT 12.1.0 detects warning, due to compiler flags used, it treated as an error, GCC 11.2 ignored this condition.

### ISSUE THREAD

**Issue by nthcomputing** [AdaCore/florist#9]
Hi,
After I submitted my pull request for compilation fix and a feature add, I moved back to Simon Wright's GCC 12.1.0 for MacOS X86_64 compiler on Ventura with Xcode 14.1, I was using GCC 11.2 with Xcode 12 on Catalina.  Using the fixes in my forked branch, compilation worked until a new warning appeared during the final building that stops everything (this doesn't occur in GCC 11.2).

posix-signals.ads:119:32: warning: null range [enabled by default]
gprbuild: *** compilation phase failed

On MacOS this actually what you want!  I looked at the line and it defines the realtime signal range, MacOS/BSD doesn't have this at all, so a null range is a perfect answer...however you used -gnatg in the gprbuild line, so ALL warnings are now errors.  I cannot simply change anything in the code because this actually a good solution.  

Can you look into removing the -gnatg requirement to allow this warning to pass as expected behavior?

**Comment by Fabien-Chouteau** [comment]
Hello @nthcomputing,

The best fix in this situation might be to disable the warning locally in the code with a `pragma Warnings`:
```Ada
   pragma Warnings (Off, "null range");
   subtype Realtime_Signal is Signal range
     Signal (POSIX.C.SIGRTMIN) .. POSIX.C.SIGRTMAX;
   pragma Warnings (On, "null range");
```
Of course with a comment to explain why the warning is disabled.

The flag that treats warnings as error is actually `-gnatwae`, and it is not used in the `Production` build mode (default). So if you  only want to use this library you can build in this mode and this warning will not be a problem.

**Comment by nthcomputing** [comment]
This is good & fair solution, it hit me when I was reading this that you can even do this in Ada, I've abandoned my C++ days when we did this all the time.  In all my years in Ada I never/ever turned off a compiler warning or error...it was never the right call.  I really forgot you could even do this...I feel foolish asking now :-) 

You're right, I'll try this and see where the next issue pops up.  I'll update the comments and such when I do this.  I should have remembered...

**Comment by nthcomputing** [comment]
That was my only blocker on GCC 12.1.0, so after that...it was smooth sailing.
